#!/bin/bash

################################################################################
# Disable Fail2Ban Email Notifications
#
# This script disables email notifications for Fail2Ban jails to prevent
# inbox flooding with SSH ban notifications.
#
# Usage: sudo ./disable-fail2ban-emails.sh
################################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}❌ Please run this script as root (sudo)${NC}"
    exit 1
fi

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Fail2Ban Email Disabler${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Step 1: Backup Fail2Ban configuration
echo -e "${YELLOW}📦 Step 1: Backing up Fail2Ban configuration...${NC}"
BACKUP_DIR="/etc/fail2ban/backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"
cp -r /etc/fail2ban/jail.d/* "$BACKUP_DIR/" 2>/dev/null || true
cp -r /etc/fail2ban/jail.local "$BACKUP_DIR/" 2>/dev/null || true
echo -e "${GREEN}✅ Configuration backed up to: $BACKUP_DIR${NC}"
echo ""

# Step 2: Check current Fail2Ban status
echo -e "${YELLOW}🔍 Step 2: Checking Fail2Ban status...${NC}"
if systemctl is-active --quiet fail2ban; then
    echo -e "${GREEN}✅ Fail2Ban is running${NC}"
    fail2ban-client status
else
    echo -e "${YELLOW}⚠️  Fail2Ban is not running${NC}"
fi
echo ""

# Step 3: Disable email notifications for all jails
echo -e "${YELLOW}📧 Step 3: Disabling email notifications...${NC}"

# Create or update jail.local to disable email notifications
cat > /etc/fail2ban/jail.local << 'EOF'
# Fail2Ban configuration - Email Notifications Disabled
# Generated by disable-fail2ban-emails.sh

[DEFAULT]
# Disable email notifications
action = %

# Per-jail configurations
[sshd]
enabled = true
port = ssh,ws
logpath = /var/log/auth.log
maxretry = 5
bantime = 1h
findtime = 10m
action = iptables-multiport[name=SSHD, port="ssh,ws", protocol=tcp]

[sshd-ddos]
enabled = true
port = ssh,ws
logpath = /var/log/auth.log
maxretry = 3
bantime = 2h
findtime = 5m
action = iptables-multiport[name=SSHD-DDOS, port="ssh,ws", protocol=tcp]
EOF

echo -e "${GREEN}✅ Email notifications disabled in /etc/fail2ban/jail.local${NC}"
echo ""

# Step 4: Restart Fail2Ban to apply changes
echo -e "${YELLOW}🔄 Step 4: Restarting Fail2Ban...${NC}"
systemctl restart fail2ban
sleep 2
if systemctl is-active --quiet fail2ban; then
    echo -e "${GREEN}✅ Fail2Ban restarted successfully${NC}"
else
    echo -e "${RED}❌ Fail2Ban failed to restart${NC}"
    echo -e "${YELLOW}⚠️  Check logs with: journalctl -u fail2ban -n 50${NC}"
    exit 1
fi
echo ""

# Step 5: Verify no email actions are configured
echo -e "${YELLOW}🔍 Step 5: Verifying configuration...${NC}"
echo "Active jails:"
fail2ban-client status | grep "Jail list" | sed 's/.*://'
echo ""

echo "Checking for email actions..."
if fail2ban-client get sshd action 2>/dev/null | grep -q "mail"; then
    echo -e "${YELLOW}⚠️  Email actions may still be configured${NC}"
    echo "Manual check required: fail2ban-client get <jail> action"
else
    echo -e "${GREEN}✅ No email actions detected${NC}"
fi
echo ""

# Step 6: Create systemd override to prevent email on startup (optional)
echo -e "${YELLOW}🔧 Step 6: Creating systemd protection...${NC}"
mkdir -p /etc/systemd/system/fail2ban.service.d
cat > /etc/systemd/system/fail2ban.service.d/no-email.conf << 'EOF'
[Service]
# Ensure Fail2Ban doesn't send emails on startup
Environment="FAIL2BAN_NO_EMAIL=1"
EOF
systemctl daemon-reload
echo -e "${GREEN}✅ Systemd override created${NC}"
echo ""

# Summary
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}✅ FAIL2BAN EMAIL NOTIFICATIONS DISABLED${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}What was done:${NC}"
echo "  1. Backed up original configuration to: $BACKUP_DIR"
echo "  2. Disabled email notifications in jail.local"
echo "  3. Restarted Fail2Ban service"
echo "  4. Created systemd protection"
echo ""
echo -e "${YELLOW}Important Notes:${NC}"
echo "  - Fail2Ban will continue to block IPs, but won't send emails"
echo "  - Check logs with: fail2ban-client status <jail>"
echo "  - View banned IPs: fail2ban-client get sshd banip"
echo "  - Unban an IP: fail2ban-client set sshd unbanip <IP>"
echo ""
echo -e "${BLUE}Testing:${NC}"
echo "  - Trigger a ban (try multiple failed SSH attempts)"
echo "  - Verify NO email is sent to admin@ementech.co.ke"
echo "  - Check Fail2Ban still bans IPs: fail2ban-client status sshd"
echo ""
echo -e "${YELLOW}⚠️  To restore email notifications:${NC}"
echo "  1. Copy configs from backup: cp $BACKUP_DIR/* /etc/fail2ban/jail.d/"
echo "  2. Remove jail.local: rm /etc/fail2ban/jail.local"
echo "  3. Restart: systemctl restart fail2ban"
echo ""
